[workspace]
authors = ["ozzyozbourne <khanosaid726@gmail.com>"]
channels = ["https://conda.modular.com/max-nightly", "conda-forge"]
name = "gpumode"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
mojo = "<1.0.0"
