apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-config
  namespace: mongodb
data: 
  mongod.conf: |
    storage:
      dbPath: /data/db
    replication:
      replSetName: rs0
    net: 
      bindIp: 0.0.0.0
