services:
  redis:
    image: redis:latest  
    container_name: my-redis
    restart: unless-stopped
    ports:
      - "6379:6379"  
    volumes:
      - redis-data:/data  
    command: redis-server --appendonly yes --requirepass myStrongPassword
    environment:
      - TZ=UTC  
    networks:
      - redis-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
      
  redisinsight:
    image: redis/redisinsight:latest
    container_name: redisinsight
    restart: unless-stopped
    ports:
      - "5540:5540"
    volumes:
      - redisinsight-data:/data
    networks:
      - redis-network
    depends_on:
      - redis

networks:
  redis-network:
    driver: bridge
    
volumes:
  redis-data:
    driver: local
  redisinsight-data:
    driver: local
