version: '3.8'

services:
  redis:
    image: redis:latest  
    container_name: my-redis
    restart: unless-stopped
    ports:
      - "6379:6379"  
    volumes:
      - redis-data:/data  
    command: redis-server --appendonly yes --requirepass myStrongPassword
    environment:
      - TZ=UTC  
    networks:
      - redis-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  redis-network:
    driver: bridge

volumes:
  redis-data:
    driver: local
