# atomic
main.init STEXT size=16 args=0x0 locals=0x0 funcid=0x0 align=0x0 leaf
	0x0000 00000 (<autogenerated>:1)	TEXT	main.init(SB), LEAF|NOFRAME|PKGINIT|ABIInternal, $0-0
	0x0000 00000 (<autogenerated>:1)	FUNCDATA	$0, gclocals·FzY36IO2mY0y4dZ1+Izd/w==(SB)
	0x0000 00000 (<autogenerated>:1)	FUNCDATA	$1, gclocals·FzY36IO2mY0y4dZ1+Izd/w==(SB)
	0x0000 00000 (<autogenerated>:1)	RET	(R30)
	0x0000 c0 03 5f d6 00 00 00 00 00 00 00 00 00 00 00 00  .._.............
main.incrementCounter STEXT size=112 args=0x0 locals=0x18 funcid=0x0 align=0x0
	0x0000 00000 (/Users/ozzy/lab/go/atomic/main.go:14)	TEXT	main.incrementCounter(SB), ABIInternal, $32-0
	0x0000 00000 (/Users/ozzy/lab/go/atomic/main.go:14)	MOVD	16(g), R16
	0x0004 00004 (/Users/ozzy/lab/go/atomic/main.go:14)	PCDATA	$0, $-2
	0x0004 00004 (/Users/ozzy/lab/go/atomic/main.go:14)	CMP	R16, RSP
	0x0008 00008 (/Users/ozzy/lab/go/atomic/main.go:14)	BLS	92
	0x000c 00012 (/Users/ozzy/lab/go/atomic/main.go:14)	PCDATA	$0, $-1
	0x000c 00012 (/Users/ozzy/lab/go/atomic/main.go:14)	MOVD.W	R30, -32(RSP)
	0x0010 00016 (/Users/ozzy/lab/go/atomic/main.go:14)	MOVD	R29, -8(RSP)
	0x0014 00020 (/Users/ozzy/lab/go/atomic/main.go:14)	SUB	$8, RSP, R29
	0x0018 00024 (/Users/ozzy/lab/go/atomic/main.go:14)	FUNCDATA	$0, gclocals·FzY36IO2mY0y4dZ1+Izd/w==(SB)
	0x0018 00024 (/Users/ozzy/lab/go/atomic/main.go:14)	FUNCDATA	$1, gclocals·FzY36IO2mY0y4dZ1+Izd/w==(SB)
	0x0018 00024 (/Users/ozzy/lab/go/atomic/main.go:15)	MOVD	$main.mutex(SB), R0
	0x0020 00032 (/Users/ozzy/lab/go/atomic/main.go:15)	PCDATA	$1, $0
	0x0020 00032 (/Users/ozzy/lab/go/atomic/main.go:15)	CALL	sync.(*Mutex).Lock(SB)
	0x0024 00036 (/Users/ozzy/lab/go/atomic/main.go:15)	PCDATA	$0, $-3
	0x0024 00036 (/Users/ozzy/lab/go/atomic/main.go:16)	MOVD	main.counter(SB), R1
	0x002c 00044 (/Users/ozzy/lab/go/atomic/main.go:16)	PCDATA	$0, $-1
	0x002c 00044 (/Users/ozzy/lab/go/atomic/main.go:16)	ADD	$1, R1, R1
	0x0030 00048 (/Users/ozzy/lab/go/atomic/main.go:16)	PCDATA	$0, $-4
	0x0030 00048 (/Users/ozzy/lab/go/atomic/main.go:16)	MOVD	R1, main.counter(SB)
	0x0038 00056 (/Users/ozzy/lab/go/atomic/main.go:16)	PCDATA	$0, $-1
	0x0038 00056 (/Users/ozzy/lab/go/atomic/main.go:17)	MOVD	$main.mutex(SB), R0
	0x0040 00064 (/Users/ozzy/lab/go/atomic/main.go:17)	CALL	sync.(*Mutex).Unlock(SB)
	0x0044 00068 (/Users/ozzy/lab/go/atomic/main.go:18)	MOVD	$main.wg(SB), R0
	0x004c 00076 (/Users/ozzy/lab/go/atomic/main.go:18)	CALL	sync.(*WaitGroup).Done(SB)
	0x0050 00080 (/Users/ozzy/lab/go/atomic/main.go:19)	MOVD	-8(RSP), R29
	0x0054 00084 (/Users/ozzy/lab/go/atomic/main.go:19)	MOVD.P	32(RSP), R30
	0x0058 00088 (/Users/ozzy/lab/go/atomic/main.go:19)	RET	(R30)
	0x005c 00092 (/Users/ozzy/lab/go/atomic/main.go:19)	NOP
	0x005c 00092 (/Users/ozzy/lab/go/atomic/main.go:14)	PCDATA	$1, $-1
	0x005c 00092 (/Users/ozzy/lab/go/atomic/main.go:14)	PCDATA	$0, $-2
	0x005c 00092 (/Users/ozzy/lab/go/atomic/main.go:14)	MOVD	R30, R3
	0x0060 00096 (/Users/ozzy/lab/go/atomic/main.go:14)	CALL	runtime.morestack_noctxt(SB)
	0x0064 00100 (/Users/ozzy/lab/go/atomic/main.go:14)	PCDATA	$0, $-1
	0x0064 00100 (/Users/ozzy/lab/go/atomic/main.go:14)	JMP	0
	0x0000 90 0b 40 f9 ff 63 30 eb a9 02 00 54 fe 0f 1e f8  ..@..c0....T....
	0x0010 fd 83 1f f8 fd 23 00 d1 00 00 00 90 00 00 00 91  .....#..........
	0x0020 00 00 00 94 1b 00 00 90 61 03 40 f9 21 04 00 91  ........a.@.!...
	0x0030 1b 00 00 90 61 03 00 f9 00 00 00 90 00 00 00 91  ....a...........
	0x0040 00 00 00 94 00 00 00 90 00 00 00 91 00 00 00 94  ................
	0x0050 fd 83 5f f8 fe 07 42 f8 c0 03 5f d6 e3 03 1e aa  .._...B..._.....
	0x0060 00 00 00 94 e7 ff ff 17 00 00 00 00 00 00 00 00  ................
	rel 24+8 t=R_ADDRARM64 main.mutex+0
	rel 32+4 t=R_CALLARM64 sync.(*Mutex).Lock+0
	rel 36+8 t=R_ARM64_PCREL_LDST64 main.counter+0
	rel 48+8 t=R_ARM64_PCREL_LDST64 main.counter+0
	rel 56+8 t=R_ADDRARM64 main.mutex+0
	rel 64+4 t=R_CALLARM64 sync.(*Mutex).Unlock+0
	rel 68+8 t=R_ADDRARM64 main.wg+0
	rel 76+4 t=R_CALLARM64 sync.(*WaitGroup).Done+0
	rel 96+4 t=R_CALLARM64 runtime.morestack_noctxt+0
main.main STEXT size=272 args=0x0 locals=0x68 funcid=0x0 align=0x0
	0x0000 00000 (/Users/ozzy/lab/go/atomic/main.go:21)	TEXT	main.main(SB), ABIInternal, $112-0
	0x0000 00000 (/Users/ozzy/lab/go/atomic/main.go:21)	MOVD	16(g), R16
	0x0004 00004 (/Users/ozzy/lab/go/atomic/main.go:21)	PCDATA	$0, $-2
	0x0004 00004 (/Users/ozzy/lab/go/atomic/main.go:21)	CMP	R16, RSP
	0x0008 00008 (/Users/ozzy/lab/go/atomic/main.go:21)	BLS	260
	0x000c 00012 (/Users/ozzy/lab/go/atomic/main.go:21)	PCDATA	$0, $-1
	0x000c 00012 (/Users/ozzy/lab/go/atomic/main.go:21)	MOVD.W	R30, -112(RSP)
	0x0010 00016 (/Users/ozzy/lab/go/atomic/main.go:21)	MOVD	R29, -8(RSP)
	0x0014 00020 (/Users/ozzy/lab/go/atomic/main.go:21)	SUB	$8, RSP, R29
	0x0018 00024 (/Users/ozzy/lab/go/atomic/main.go:21)	FUNCDATA	$0, gclocals·ISb46fRPFoZ9pIfykFK/kQ==(SB)
	0x0018 00024 (/Users/ozzy/lab/go/atomic/main.go:21)	FUNCDATA	$1, gclocals·d0djADgTbzbBGCnVNOtE5w==(SB)
	0x0018 00024 (/Users/ozzy/lab/go/atomic/main.go:21)	FUNCDATA	$2, main.main.stkobj(SB)
	0x0018 00024 (/Users/ozzy/lab/go/atomic/main.go:22)	MOVD	ZR, main..autotmp_1-64(SP)
	0x001c 00028 (/Users/ozzy/lab/go/atomic/main.go:22)	MOVD	$1000, R2
	0x0020 00032 (/Users/ozzy/lab/go/atomic/main.go:22)	MOVD	R2, main..autotmp_2-72(SP)
	0x0024 00036 (/Users/ozzy/lab/go/atomic/main.go:22)	JMP	40
	0x0028 00040 (/Users/ozzy/lab/go/atomic/main.go:22)	MOVD	main..autotmp_2-72(SP), R2
	0x002c 00044 (/Users/ozzy/lab/go/atomic/main.go:22)	MOVD	main..autotmp_1-64(SP), R3
	0x0030 00048 (/Users/ozzy/lab/go/atomic/main.go:22)	CMP	R3, R2
	0x0034 00052 (/Users/ozzy/lab/go/atomic/main.go:22)	BGT	60
	0x0038 00056 (/Users/ozzy/lab/go/atomic/main.go:22)	JMP	108
	0x003c 00060 (/Users/ozzy/lab/go/atomic/main.go:23)	MOVD	$main.wg(SB), R0
	0x0044 00068 (/Users/ozzy/lab/go/atomic/main.go:23)	MOVD	$1, R1
	0x0048 00072 (/Users/ozzy/lab/go/atomic/main.go:23)	PCDATA	$1, $0
	0x0048 00072 (/Users/ozzy/lab/go/atomic/main.go:23)	CALL	sync.(*WaitGroup).Add(SB)
	0x004c 00076 (/Users/ozzy/lab/go/atomic/main.go:24)	MOVD	$main.incrementCounter·f(SB), R0
	0x0054 00084 (/Users/ozzy/lab/go/atomic/main.go:24)	CALL	runtime.newproc(SB)
	0x0058 00088 (/Users/ozzy/lab/go/atomic/main.go:24)	JMP	92
	0x005c 00092 (/Users/ozzy/lab/go/atomic/main.go:22)	MOVD	main..autotmp_1-64(SP), R2
	0x0060 00096 (/Users/ozzy/lab/go/atomic/main.go:22)	ADD	$1, R2, R2
	0x0064 00100 (/Users/ozzy/lab/go/atomic/main.go:22)	MOVD	R2, main..autotmp_1-64(SP)
	0x0068 00104 (/Users/ozzy/lab/go/atomic/main.go:22)	JMP	40
	0x006c 00108 (/Users/ozzy/lab/go/atomic/main.go:27)	MOVD	$main.wg(SB), R0
	0x0074 00116 (/Users/ozzy/lab/go/atomic/main.go:27)	CALL	sync.(*WaitGroup).Wait(SB)
	0x0078 00120 (/Users/ozzy/lab/go/atomic/main.go:28)	STP	(ZR, ZR), main..autotmp_0-16(SP)
	0x007c 00124 (/Users/ozzy/lab/go/atomic/main.go:28)	MOVD	$main..autotmp_0-16(SP), R1
	0x0080 00128 (/Users/ozzy/lab/go/atomic/main.go:28)	MOVD	R1, main..autotmp_4-48(SP)
	0x0084 00132 (/Users/ozzy/lab/go/atomic/main.go:28)	PCDATA	$0, $-3
	0x0084 00132 (/Users/ozzy/lab/go/atomic/main.go:28)	MOVD	main.counter(SB), R0
	0x008c 00140 (/Users/ozzy/lab/go/atomic/main.go:28)	PCDATA	$0, $-1
	0x008c 00140 (/Users/ozzy/lab/go/atomic/main.go:28)	PCDATA	$1, $1
	0x008c 00140 (/Users/ozzy/lab/go/atomic/main.go:28)	CALL	runtime.convT64(SB)
	0x0090 00144 (/Users/ozzy/lab/go/atomic/main.go:28)	MOVD	R0, main..autotmp_5-56(SP)
	0x0094 00148 (/Users/ozzy/lab/go/atomic/main.go:28)	MOVD	main..autotmp_4-48(SP), R1
	0x0098 00152 (/Users/ozzy/lab/go/atomic/main.go:28)	PCDATA	$0, $-2
	0x0098 00152 (/Users/ozzy/lab/go/atomic/main.go:28)	MOVB	(R1), R27
	0x009c 00156 (/Users/ozzy/lab/go/atomic/main.go:28)	PCDATA	$0, $-1
	0x009c 00156 (/Users/ozzy/lab/go/atomic/main.go:28)	MOVD	$type:int(SB), R2
	0x00a4 00164 (/Users/ozzy/lab/go/atomic/main.go:28)	MOVD	R2, (R1)
	0x00a8 00168 (/Users/ozzy/lab/go/atomic/main.go:28)	PCDATA	$0, $-4
	0x00a8 00168 (/Users/ozzy/lab/go/atomic/main.go:28)	MOVWU	runtime.writeBarrier(SB), R2
	0x00b0 00176 (/Users/ozzy/lab/go/atomic/main.go:28)	PCDATA	$0, $-1
	0x00b0 00176 (/Users/ozzy/lab/go/atomic/main.go:28)	PCDATA	$0, $-2
	0x00b0 00176 (/Users/ozzy/lab/go/atomic/main.go:28)	CBZW	R2, 184
	0x00b4 00180 (/Users/ozzy/lab/go/atomic/main.go:28)	JMP	188
	0x00b8 00184 (/Users/ozzy/lab/go/atomic/main.go:28)	JMP	208
	0x00bc 00188 (/Users/ozzy/lab/go/atomic/main.go:28)	CALL	runtime.gcWriteBarrier2(SB)
	0x00c0 00192 (/Users/ozzy/lab/go/atomic/main.go:28)	MOVD	R0, (R25)
	0x00c4 00196 (/Users/ozzy/lab/go/atomic/main.go:28)	MOVD	8(R1), R3
	0x00c8 00200 (/Users/ozzy/lab/go/atomic/main.go:28)	MOVD	R3, 8(R25)
	0x00cc 00204 (/Users/ozzy/lab/go/atomic/main.go:28)	JMP	208
	0x00d0 00208 (/Users/ozzy/lab/go/atomic/main.go:28)	MOVD	R0, 8(R1)
	0x00d4 00212 (/Users/ozzy/lab/go/atomic/main.go:28)	PCDATA	$0, $-1
	0x00d4 00212 (/Users/ozzy/lab/go/atomic/main.go:28)	MOVD	main..autotmp_4-48(SP), R0
	0x00d8 00216 (/Users/ozzy/lab/go/atomic/main.go:28)	PCDATA	$0, $-2
	0x00d8 00216 (/Users/ozzy/lab/go/atomic/main.go:28)	MOVB	(R0), R27
	0x00dc 00220 (/Users/ozzy/lab/go/atomic/main.go:28)	PCDATA	$0, $-1
	0x00dc 00220 (/Users/ozzy/lab/go/atomic/main.go:28)	JMP	224
	0x00e0 00224 (/Users/ozzy/lab/go/atomic/main.go:28)	MOVD	R0, main..autotmp_3-40(SP)
	0x00e4 00228 (/Users/ozzy/lab/go/atomic/main.go:28)	MOVD	$1, R2
	0x00e8 00232 (/Users/ozzy/lab/go/atomic/main.go:28)	MOVD	R2, main..autotmp_3-32(SP)
	0x00ec 00236 (/Users/ozzy/lab/go/atomic/main.go:28)	MOVD	R2, main..autotmp_3-24(SP)
	0x00f0 00240 (/Users/ozzy/lab/go/atomic/main.go:28)	MOVD	R2, R1
	0x00f4 00244 (/Users/ozzy/lab/go/atomic/main.go:28)	PCDATA	$1, $0
	0x00f4 00244 (/Users/ozzy/lab/go/atomic/main.go:28)	CALL	fmt.Println(SB)
	0x00f8 00248 (/Users/ozzy/lab/go/atomic/main.go:29)	MOVD	-8(RSP), R29
	0x00fc 00252 (/Users/ozzy/lab/go/atomic/main.go:29)	MOVD.P	112(RSP), R30
	0x0100 00256 (/Users/ozzy/lab/go/atomic/main.go:29)	RET	(R30)
	0x0104 00260 (/Users/ozzy/lab/go/atomic/main.go:29)	NOP
	0x0104 00260 (/Users/ozzy/lab/go/atomic/main.go:21)	PCDATA	$1, $-1
	0x0104 00260 (/Users/ozzy/lab/go/atomic/main.go:21)	PCDATA	$0, $-2
	0x0104 00260 (/Users/ozzy/lab/go/atomic/main.go:21)	MOVD	R30, R3
	0x0108 00264 (/Users/ozzy/lab/go/atomic/main.go:21)	CALL	runtime.morestack_noctxt(SB)
	0x010c 00268 (/Users/ozzy/lab/go/atomic/main.go:21)	PCDATA	$0, $-1
	0x010c 00268 (/Users/ozzy/lab/go/atomic/main.go:21)	JMP	0
	0x0000 90 0b 40 f9 ff 63 30 eb e9 07 00 54 fe 0f 19 f8  ..@..c0....T....
	0x0010 fd 83 1f f8 fd 23 00 d1 ff 17 00 f9 02 7d 80 d2  .....#.......}..
	0x0020 e2 13 00 f9 01 00 00 14 e2 13 40 f9 e3 17 40 f9  ..........@...@.
	0x0030 5f 00 03 eb 4c 00 00 54 0d 00 00 14 00 00 00 90  _...L..T........
	0x0040 00 00 00 91 e1 03 40 b2 00 00 00 94 00 00 00 90  ......@.........
	0x0050 00 00 00 91 00 00 00 94 01 00 00 14 e2 17 40 f9  ..............@.
	0x0060 42 04 00 91 e2 17 00 f9 f0 ff ff 17 00 00 00 90  B...............
	0x0070 00 00 00 91 00 00 00 94 ff ff 05 a9 e1 63 01 91  .............c..
	0x0080 e1 1f 00 f9 1b 00 00 90 60 03 40 f9 00 00 00 94  ........`.@.....
	0x0090 e0 1b 00 f9 e1 1f 40 f9 3b 00 80 39 02 00 00 90  ......@.;..9....
	0x00a0 42 00 00 91 22 00 00 f9 1b 00 00 90 62 03 40 b9  B...".......b.@.
	0x00b0 42 00 00 34 02 00 00 14 06 00 00 14 00 00 00 94  B..4............
	0x00c0 20 03 00 f9 23 04 40 f9 23 07 00 f9 01 00 00 14   ...#.@.#.......
	0x00d0 20 04 00 f9 e0 1f 40 f9 1b 00 80 39 01 00 00 14   .....@....9....
	0x00e0 e0 23 00 f9 e2 03 40 b2 e2 27 00 f9 e2 2b 00 f9  .#....@..'...+..
	0x00f0 e1 03 02 aa 00 00 00 94 fd 83 5f f8 fe 07 47 f8  .........._...G.
	0x0100 c0 03 5f d6 e3 03 1e aa 00 00 00 94 bd ff ff 17  .._.............
	rel 0+0 t=R_USEIFACE type:int+0
	rel 60+8 t=R_ADDRARM64 main.wg+0
	rel 72+4 t=R_CALLARM64 sync.(*WaitGroup).Add+0
	rel 76+8 t=R_ADDRARM64 main.incrementCounter·f+0
	rel 84+4 t=R_CALLARM64 runtime.newproc+0
	rel 108+8 t=R_ADDRARM64 main.wg+0
	rel 116+4 t=R_CALLARM64 sync.(*WaitGroup).Wait+0
	rel 132+8 t=R_ARM64_PCREL_LDST64 main.counter+0
	rel 140+4 t=R_CALLARM64 runtime.convT64+0
	rel 156+8 t=R_ADDRARM64 type:int+0
	rel 168+8 t=R_ARM64_PCREL_LDST32 runtime.writeBarrier+0
	rel 188+4 t=R_CALLARM64 runtime.gcWriteBarrier2+0
	rel 244+4 t=R_CALLARM64 fmt.Println+0
	rel 264+4 t=R_CALLARM64 runtime.morestack_noctxt+0
go:cuinfo.producer.main SDWARFCUINFO dupok size=0
	0x0000 2d 4e 20 2d 6c 20 2d 73 68 61 72 65 64 20 72 65  -N -l -shared re
	0x0010 67 61 62 69                                      gabi
go:cuinfo.packagename.main SDWARFCUINFO dupok size=0
	0x0000 6d 61 69 6e                                      main
main..inittask SNOPTRDATA size=8
	0x0000 00 00 00 00 00 00 00 00                          ........
	rel 0+0 t=R_INITORDER fmt..inittask+0
	rel 0+0 t=R_INITORDER sync..inittask+0
main.counter SNOPTRBSS size=8
 SDWARFVAR size=29
	0x0000 0a 6d 61 69 6e 2e 63 6f 75 6e 74 65 72 00 09 03  .main.counter...
	0x0010 00 00 00 00 00 00 00 00 00 00 00 00 01           .............
	rel 16+8 t=R_ADDR main.counter+0
	rel 24+4 t=R_DWARFSECREF go:info.int+0
main.wg SNOPTRBSS size=16
 SDWARFVAR size=24
	0x0000 0a 6d 61 69 6e 2e 77 67 00 09 03 00 00 00 00 00  .main.wg........
	0x0010 00 00 00 00 00 00 00 01                          ........
	rel 11+8 t=R_ADDR main.wg+0
	rel 19+4 t=R_DWARFSECREF go:info.sync.WaitGroup+0
main.mutex SNOPTRBSS size=8
 SDWARFVAR size=27
	0x0000 0a 6d 61 69 6e 2e 6d 75 74 65 78 00 09 03 00 00  .main.mutex.....
	0x0010 00 00 00 00 00 00 00 00 00 00 01                 ...........
	rel 14+8 t=R_ADDR main.mutex+0
	rel 22+4 t=R_DWARFSECREF go:info.sync.Mutex+0
runtime.memequal64·f SRODATA dupok size=8
	0x0000 00 00 00 00 00 00 00 00                          ........
	rel 0+8 t=R_ADDR runtime.memequal64+0
runtime.gcbits.0100000000000000 SRODATA dupok size=8
	0x0000 01 00 00 00 00 00 00 00                          ........
type:.namedata.*[1]interface {}- SRODATA dupok size=18
	0x0000 00 10 2a 5b 31 5d 69 6e 74 65 72 66 61 63 65 20  ..*[1]interface 
	0x0010 7b 7d                                            {}
runtime.nilinterequal·f SRODATA dupok size=8
	0x0000 00 00 00 00 00 00 00 00                          ........
	rel 0+8 t=R_ADDR runtime.nilinterequal+0
runtime.gcbits.0200000000000000 SRODATA dupok size=8
	0x0000 02 00 00 00 00 00 00 00                          ........
type:[1]interface {} SRODATA dupok size=72
	0x0000 10 00 00 00 00 00 00 00 10 00 00 00 00 00 00 00  ................
	0x0010 ea 37 5e 5e 02 08 08 11 00 00 00 00 00 00 00 00  .7^^............
	0x0020 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	0x0030 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	0x0040 01 00 00 00 00 00 00 00                          ........
	rel 24+8 t=R_ADDR runtime.nilinterequal·f+0
	rel 32+8 t=R_ADDR runtime.gcbits.0200000000000000+0
	rel 40+4 t=R_ADDROFF type:.namedata.*[1]interface {}-+0
	rel 44+4 t=RelocType(-32763) type:*[1]interface {}+0
	rel 48+8 t=R_ADDR type:interface {}+0
	rel 56+8 t=R_ADDR type:[]interface {}+0
type:*[1]interface {} SRODATA dupok size=56
	0x0000 08 00 00 00 00 00 00 00 08 00 00 00 00 00 00 00  ................
	0x0010 73 3b a6 1c 08 08 08 36 00 00 00 00 00 00 00 00  s;.....6........
	0x0020 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	0x0030 00 00 00 00 00 00 00 00                          ........
	rel 24+8 t=R_ADDR runtime.memequal64·f+0
	rel 32+8 t=R_ADDR runtime.gcbits.0100000000000000+0
	rel 40+4 t=R_ADDROFF type:.namedata.*[1]interface {}-+0
	rel 48+8 t=R_ADDR type:[1]interface {}+0
main.incrementCounter·f SRODATA dupok size=8
	0x0000 00 00 00 00 00 00 00 00                          ........
	rel 0+8 t=R_ADDR main.incrementCounter+0
gclocals·FzY36IO2mY0y4dZ1+Izd/w== SRODATA dupok size=8
	0x0000 01 00 00 00 00 00 00 00                          ........
gclocals·ISb46fRPFoZ9pIfykFK/kQ== SRODATA dupok size=8
	0x0000 02 00 00 00 00 00 00 00                          ........
gclocals·d0djADgTbzbBGCnVNOtE5w== SRODATA dupok size=10
	0x0000 02 00 00 00 07 00 00 00 00 02                    ..........
main.main.stkobj SRODATA static size=24
	0x0000 01 00 00 00 00 00 00 00 f0 ff ff ff 10 00 00 00  ................
	0x0010 10 00 00 00 00 00 00 00                          ........
	rel 20+4 t=R_ADDROFF runtime.gcbits.0200000000000000+0
